### PR TITLE
Profile.js

### PR DESCRIPTION
**Pull request by ashyudhajit**
Change server ip to lux's ip.

### CODE REVIEW

**Comment by SilverTactic** [comment]
Dude, you literally copied Gold's profile directly ._.
Gold uses stuff from other files. You can't copy it that way

**Comment by ashyudhajit** [comment]
Ik

**Comment by ashyudhajit** [comment]
Also check my second profile 
Code.And say who's code is that

.

**Comment by ashyudhajit** [comment]
Lol its mine.

**Pull request merged**
